### ISSUE TITLE
[O] test

### ISSUE THREAD

**Issue by donaldli2020** [afkvido/afkvido.github.io#19]
### Describe your issue

testing issues

### Date of submittion

2022-02-05

### Before submitting an issue

- [x] This wasn't already submitted.
(I have checked every issue on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by donaldli2020** [comment]
COOL!

**Comment by donaldli2020** [comment]
(please delete this)

**Comment by afkvido** [comment]
Ayyyyy! My Issue templates work!

I tested them myself, but having someone else confirm it is nice.

**Comment by afkvido** [comment]
\************************************************************************************

**Comment by afkvido** [comment]
ACTUALLY, WAIT. I forgot to add the [Open] label to empty issues

**Comment by afkvido** [comment]
Thanks for making the templates donaldli!
