### ISSUE TITLE
I am board

### ISSUE THREAD

**Issue by afkvido** [afkvido/afkvido.github.io#2]
I am board, someone fix this

**Comment by afkvido** [comment]
@donaldli2020 please sir do you know how to fix this issue

**Comment by donaldli2020** [comment]
[Google](google.com/search?q=How+to+not+be+bored&oq=How+to+not+be+bored&aqs=chrome..69i57.6875j0j1&sourceid=chrome&ie=UTF-8)

**Comment by afkvido** [comment]
well… i followed your link…

here's some of the people also ask results:

![image](https://user-images.githubusercontent.com/69060894/150627115-628af270-20c0-4f90-b590-754f4198eafd.jpeg)
<p></p>
![image](https://user-images.githubusercontent.com/69060894/150627135-8ec44ebf-cb88-42bf-9efb-be892b97dad6.jpeg)
<p></p>
![image](https://user-images.githubusercontent.com/69060894/150627142-458532b9-6451-42c5-8e1a-1e8c0f08d54b.jpeg)
<p></p>
![image](https://user-images.githubusercontent.com/69060894/150627145-0eeb2b4f-e4f6-413f-a7bd-3e011886e3c5.jpeg)

**Comment by afkvido** [comment]
> [Google](google.com/search?q=How+to+not+be+bored&oq=How+to+not+be+bored&aqs=chrome..69i57.6875j0j1&sourceid=chrome&ie=UTF-8)

I also had to quotw your reply and manually copy+paste the link, because clicking the link led me to `http://localhost/google.com/search?q=How+to+not+be+bored&oq=How+to+not+be+bored&aqs=chrome..69i57.6875j0j1&sourceid=chrome&ie=UTF-8`

**Comment by afkvido** [comment]
now that you're assigned to this issue, u must entertain me >:D

**Comment by afkvido** [comment]
+ google didnt help me.

I'm still a board.

**Comment by donaldli2020** [comment]
[idk try getting your trophies to sss](https://github-profile-trophy.vercel.app/?username=afkvido)
you already have a secret trophy

**Comment by donaldli2020** [comment]
secret trophies:
rainbow lang user - 10 languages
village elder - 10 years old account
before 2010 - make an account before 2010
joined2020 - join 2020 - you have it
all s rank - get all s rank trophies
jack of all trades - join 3 organizations

**Comment by donaldli2020** [comment]
to get jack of all trades go here: @prodigyerrorcodes

**Comment by afkvido** [comment]
> secret trophies:
> rainbow lang user - 10 languages
> village elder - 10 years old account
> before 2010 - make an account before 2010
> joined2020 - join 2020 - you have it
> all s rank - get all s rank trophies
> jack of all trades - join 3 organizations



> [idk try getting your trophies to sss](https://github-profile-trophy.vercel.app/?username=afkvido)
> you already have a secret trophy

oh cool!

**Comment by donaldli2020** [comment]
you've got jack of all trades!

**Comment by afkvido** [comment]
> you've got jack of all trades!

I've got `jack off all trades`

what

**Comment by donaldli2020** [comment]
yes see https://github-profile-trophy.vercel.app/?username=afkvido
