### ISSUE TITLE
[B] testing labels

### ISSUE THREAD

**Issue by donaldli2020** [afkvido/afkvido.github.io#23]
### Describe the bug

test

### Describe how to replicate bug

test

### Date of submittion

test

### Your browser and its version.

test

### Your operating system and the version

test

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I agree to this repository's prerequisites.
(I have read and agree to the License, Code of Conduct, and Contributing Guidelines)

**Comment by donaldli2020** [comment]
Woohoo!

**Comment by afkvido** [comment]
yayyyy!
