### ISSUE TITLE
[B] Discord

### ISSUE THREAD

**Issue by donaldli2020** [afkvido/afkvido.github.io#3]
**Describe the bug**
The Discord logo doesn't show.

**Expected behavior**
I expected the Discord logo to display correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/74021676/150612761-5c78f671-691f-4ab0-bc31-a6e67a8c1d3a.png)

**Which browser are you using**
Chrome
 
**Additional context**

**Comment by afkvido** [comment]
You expexted the discord logo to show up?
damn, ya got some high expectations kid

nah, im jk.

**Comment by donaldli2020** [comment]
lmao

**Comment by afkvido** [comment]
![image](https://user-images.githubusercontent.com/69060894/150621702-ca17b4cd-96cf-44c0-82a2-a78be0391a59.jpeg) 

idk it works fine for me

**Comment by donaldli2020** [comment]
![image](https://user-images.githubusercontent.com/74021676/150621774-cab187a6-a904-49af-bce1-65e686aebb61.png)

**Comment by donaldli2020** [comment]
![image](https://user-images.githubusercontent.com/74021676/150621844-8e8bbf94-26fc-4001-87fb-c8b2b70a140d.png)

**Comment by afkvido** [comment]
The discord logo links to this image: https://discord.com/assets/07dca80a102d4149e9736d4b162cff6f.ico

which previews as ![](https://discord.com/assets/07dca80a102d4149e9736d4b162cff6f.ico)

**Comment by donaldli2020** [comment]
error 1020 when i click it

**Comment by donaldli2020** [comment]
but the commented image shows

**Comment by afkvido** [comment]
> error 1020 when i click it

dsc.bio broke, I'm looking for a better discord page

**Comment by donaldli2020** [comment]
https://user-images.githubusercontent.com/74021676/150680433-9bc9186a-6a37-4b5c-80d9-504db53beed9.png
Yay working link

**Comment by afkvido** [comment]
## Discord logo fixed in https://github.com/afkvido/afkvido.github.io/commit/93e6861c7210b163400e82011989efeb40df3378

**Comment by afkvido** [comment]
still gotta fix the bio tho
