### ISSUE TITLE
[B] GitHub Pages down!

### ISSUE THREAD

**Issue by donaldli2020** [afkvido/afkvido.github.io#4]
**Describe the bug**
DNS address not found

**Expected behavior**
Website's address should load quickly

**Screenshots**
Doesn't let me use screenshots

**Which browser are you using**
Chrome
 
**Additional context**

**Comment by donaldli2020** [comment]
The screenshots fail to upload.
![Uploading image.png…]()

**Comment by donaldli2020** [comment]
Correction:
The whole GitHub server is down!
We are probably all using cache.

**Comment by afkvido** [comment]
> Correction:
> The whole GitHub server is down!
> We are probably all using cache.

Wait. I cleared my cache and reloaded. The page works, try now.
https://afkvido.github.io

**Comment by afkvido** [comment]
I think it was a GitHub outage

**Comment by afkvido** [comment]
Is this fixed?

**Comment by donaldli2020** [comment]
yes
