### ISSUE TITLE
[B] title

### ISSUE THREAD

**Issue by afkvido** [afkvido/afkvido.github.io#6]
**Describe the bug**
Details arrow doesn't show up

**Expected behavior**
Details arrow should show up

**Screenshots**
![image](https://user-images.githubusercontent.com/69060894/150695439-dd456f7c-9bfb-4687-9429-dc8313c0ed78.png)

**Which browser are you using**
Google Chrome `Version 97.0.4692.99 (Official Build) (64-bit)`
I also tried it on Google Chrome Canary `Version 100.0.4848.0 (Official Build) canary (64-bit)`

**Comment by donaldli2020** [comment]
okay, this will take many steps.

**Comment by donaldli2020** [comment]
assign me

**Comment by afkvido** [comment]
Fixed

**Comment by afkvido** [comment]
I don't think anything was broken, GitHub might have been having problems

**Comment by donaldli2020** [comment]
fixed
