### ISSUE TITLE
[B] Summary arrows are missing

### ISSUE THREAD

**Issue by afkvido** [afkvido/afkvido.github.io#9]
**Describe the bug**
I can't click any of the details https://afkvido.github.io

**Expected behavior**
Details opens when I click details

**Screenshots**
https://afkvido.github.io

**Which browser are you using**
safari and macOs because I'm at school
 
**Additional context**
i can't click the links at the bottom either lmao

**Comment by donaldli2020** [comment]
works for me
p.s.
![image](https://user-images.githubusercontent.com/74021676/151464817-5298664c-f108-4334-8556-f72311a5331e.png)

**Comment by afkvido** [comment]
> works for me p.s. ![image](https://user-images.githubusercontent.com/74021676/151464817-5298664c-f108-4334-8556-f72311a5331e.png)

bruh

**Comment by afkvido** [comment]
wait ur on a chromebook?

**Comment by donaldli2020** [comment]
i am now on windows

**Comment by donaldli2020** [comment]
![image](https://user-images.githubusercontent.com/74021676/151467829-b1bea768-fcd6-4ef8-b43b-95c851b2bf9b.png)

**Comment by afkvido** [comment]
> ![image](https://user-images.githubusercontent.com/74021676/151467829-b1bea768-fcd6-4ef8-b43b-95c851b2bf9b.png)

happening to me too

**Comment by afkvido** [comment]
## Well.... I can click the details, but the arrows are missing now

**Comment by afkvido** [comment]
Fixed in https://github.com/afkvido/afkvido.github.io/commit/f7a95863611fd2eacdb6c9d5600d83dee0fba59b
